--- #YAML:1.0
name:               WWW-FMyLife
version:            0.14
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:       0
    Moose:                0.86
    Net::Ping:            0
    Sub::Override:        0
    Test::Deep:           0
    Test::MockObject::Extends:  0
    Test::More:           0.88
    XML::Simple:          2.18
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
